# Generated by Django 6.0 on 2026-01-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код доступу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Код доступу',
                'verbose_name_plural': 'Коди доступу',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва курсу')),
                ('keyword', models.CharField(max_length=50, unique=True, verbose_name='Кодове слово (з відео)')),
                ('description', models.TextField(blank=True, verbose_name='Опис (для адміна)')),
            ],
            options={
                'verbose_name': 'Міні-курс',
                'verbose_name_plural': 'Міні-курси',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='День видачі (1-5)')),
                ('time_slot', models.IntegerField(choices=[(10, '10:00'), (14, '14:00'), (18, '18:00')], verbose_name='Час видачі')),
                ('text', models.TextField(blank=True, verbose_name='Текст повідомлення')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/images/', verbose_name='Картинка')),
                ('audio', models.FileField(blank=True, null=True, upload_to='lessons/audio/', verbose_name='Аудіо')),
                ('video_note', models.FileField(blank=True, null=True, upload_to='lessons/video/', verbose_name='Відео (кружечок/файл)')),
                ('file_doc', models.FileField(blank=True, null=True, upload_to='lessons/docs/', verbose_name='Документ (PDF)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course', verbose_name='До якого курсу')),
            ],
            options={
                'verbose_name': 'Урок/Завдання',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
