# Generated by Django 6.0 on 2026-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='course_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата початку курсу'),
        ),
    ]
