# Generated by Django 6.0 on 2026-01-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botuser_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Точний текст правильного варіанту або слова', max_length=255, verbose_name='Правильна відповідь'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='error_feedback',
            field=models.TextField(blank=True, help_text="Що написати, якщо юзер помилився? Наприклад: 'Ні, це минулий час'.", verbose_name='Пояснення помилки'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', '📚 Просто теорія (читати/дивитись)'), ('quiz', '✅ Тест (кнопки з варіантами)'), ('text_input', '✍️ Вписати правильну відповідь вручну')], default='theory', max_length=20, verbose_name='Тип завдання'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_options',
            field=models.TextField(blank=True, help_text='Тільки для ТЕСТУ. Напиши варіанти, наприклад:\nApple\nBanana\nOrange', verbose_name='Варіанти відповідей (кожен з нового рядка)'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='course_start_date',
            field=models.DateTimeField(null=True, verbose_name='Дата початку курсу'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day_number',
            field=models.PositiveIntegerField(default=1, verbose_name='День видачі (1-31)'),
        ),
    ]
