# Generated by Django 6.0 on 2026-01-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_correct_answer_lesson_error_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscode',
            options={'verbose_name': 'Код доступа', 'verbose_name_plural': 'Коды доступа'},
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Мини-курс', 'verbose_name_plural': 'Мини-курс'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок/Задания', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код доступа'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='course_start_date',
            field=models.DateTimeField(null=True, verbose_name='Дата начала курса'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', verbose_name='Активный курс'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (для админа)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='keyword',
            field=models.CharField(max_length=50, unique=True, verbose_name='Кодовое слово (из видео)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Точний текст правильного варианта или слова', max_length=255, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course', verbose_name='К какому курсу'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day_number',
            field=models.PositiveIntegerField(default=1, verbose_name='День выдачи (1-31)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='error_feedback',
            field=models.TextField(blank=True, help_text="Что написать, если студент ошибся? Например: 'Нет, это прошедшее время. Обрати внимание на ...'.", verbose_name='Объяснение ошибки'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', '📚 Просто теория (читать/смотреть)'), ('quiz', '✅ Тест (кнопки с вариантами)'), ('text_input', '✍️ Вписать правильный ответ вручную')], default='theory', max_length=20, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quiz_options',
            field=models.TextField(blank=True, help_text='Только для ТЭСТА. Напиши варианты например\nApple\nBanana\nOrange', verbose_name='Варианты ответов (каждый с новой строки)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_note',
            field=models.FileField(blank=True, null=True, upload_to='lessons/video/', verbose_name='Видео (кружочек/файл)'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.botuser')),
            ],
        ),
    ]
