# Generated by Django 6.0 on 2026-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_accesscode_options_alter_botuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Тривалість (днів)'),
        ),
        migrations.AddField(
            model_name='course',
            name='finish_message',
            field=models.TextField(blank=True, default='Вітаю! Ти пройшов курс. Ось наші інші продукти: ...', verbose_name='Повідомлення при завершенні'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_slot',
            field=models.IntegerField(choices=[(10, '10:00'), (15, '15:00'), (18, '18:00')], verbose_name='Час видачі'),
        ),
    ]
