# Generated by Django 6.0 on 2026-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_duration_days_course_finish_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос (на кнопке)')),
                ('answer', models.TextField(verbose_name='Ответ (в сообщении)')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше кнопка', verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать в боте?')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'FAQ (Вопросы и ответы)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='finish_message',
            field=models.TextField(blank=True, default='Поздравляю! Ти прошёл курс. Теперь ты можешь вводить кодовое слово другого курса 😜', verbose_name='Уведомление по окончанию курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_slot',
            field=models.IntegerField(choices=[(10, '10:00'), (15, '15:00'), (18, '18:00')], verbose_name='Время выдачи'),
        ),
    ]
