# Generated by Django 6.0 on 2026-01-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faqitem_alter_course_finish_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='НЕ МЕНЯТЬ! Это имя используется в коде (например: start_message)', unique=True, verbose_name='Техническое имя (Ключ)')),
                ('text', models.TextField(help_text='Поддерживает HTML теги (<b>жирный</b>, <i>курсив</i>)', verbose_name='Текст сообщения')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Где используется (для админа)')),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Тексты бота (Приветствие, Ошибки)',
            },
        ),
    ]
