# Generated by Django 6.0 on 2026-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_botmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='current_course_day',
            field=models.IntegerField(default=0, verbose_name='Текущий день (кэш)'),
        ),
    ]
