# Generated by Django 6.0 on 2026-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_botuser_current_course_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day_number', 'time_slot', 'id'], 'verbose_name': 'Урок/Задания', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='error_feedback',
            field=models.TextField(blank=True, help_text="ВАЖНО: Количество строк должно совпадать с вариантами ответов!\n1 строка объясняет 1-й вариант, 2-я - 2-й и т.д.\nДля правильного ответа можно оставить строку пустой или написать 'Верно!'.", verbose_name='Пояснения к ответам (каждое с новой строки)'),
        ),
    ]
