# Generated by Django 6.0 on 2026-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lesson_options_alter_lesson_error_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='error_feedback',
            field=models.TextField(blank=True, help_text="ВАЖНО: Количество строк должно совпадать с вариантами ответов!<br>1 строка объясняет 1-й вариант, 2-я - 2-й и т.д.<br>Для правильного ответа можно оставить строку пустой или написать 'Верно!'.", verbose_name='Пояснения к ответам (каждое с новой строки)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quiz_options',
            field=models.TextField(blank=True, help_text='Только для ТЭСТА. Напиши варианты например<br>Apple<br>Banana<br>Orange', verbose_name='Варианты ответов (каждый с новой строки)'),
        ),
    ]
