# Generated by Django 6.0 on 2026-01-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_lesson_error_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_slot',
            field=models.IntegerField(choices=[(10, '10:00'), (14, '14:00'), (18, '18:00')], verbose_name='Время выдачи'),
        ),
    ]
