# Generated by Django 6.0 on 2026-01-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_botsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_codes', to='core.botuser', verbose_name='Кем активирован'),
        ),
    ]
