# Generated by Django 6.0 on 2026-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_accesscode_activated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_message',
            field=models.TextField(blank=True, default='🚀 <b>Отлично! Ти записан на курс.</b>\n\n📅 <b>Расписание:</b>\nМатериалы будут приходить каждый день в <b>10:00, 14:00 та 18:00</b>.\n\n⏳ <b>Старт:</b> Твой первый день начнётся <b>ЗАВТРА в 10:00</b>.\nСегодня ты можешь отдыхать и готовится!', verbose_name='Уведомление по окончанию курса'),
        ),
    ]
