# Generated by Django 5.2.10 on 2026-01-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_start_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Мини-курс', 'verbose_name_plural': 'Мини-курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day_number', 'send_time', 'id'], 'verbose_name': 'Урок/Задания', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='course_start_date',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='current_course',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='current_course_day',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='accesscode',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.course', verbose_name='Курсы, которые откроются'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='send_time',
            field=models.TimeField(default='10:00', help_text='Например: 17:43 или 09:00', verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_message',
            field=models.TextField(blank=True, default='🚀 <b>Отлично! Ти записан на курс.</b>\n\n', verbose_name='Уведомление по старту курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course', verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('current_day', models.IntegerField(default=1, verbose_name='Текущий день обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.botuser')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
