# Generated by Django 5.2.10 on 2026-01-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='keyword',
        ),
    ]
